controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_fiche_exploitation:
    path: /fiche_exploitation
    controller: App\Controller\FicheExploitationController::index
    methods: GET

app_fiche_stock:
    path: /fiche_stock
    controller: App\Controller\FicheStockController::index
    methods: GET
